version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "Eyevinn/maintainers"
    labels:
      - "dependencies"
    commit-message:
      # Use conventional commit format
      prefix: "chore"
      prefix-development: "chore"
      # Include scope in commit message
      include: "scope"
      # Disable verbose commit body to avoid line length issues
      # This will create simpler commit messages like:
      # "chore(deps): bump webpack from 5.76.0 to 5.90.0"
    groups:
      development-dependencies:
        patterns:
          - "@types/*"
          - "eslint*"
          - "prettier*"
          - "jest*"
          - "webpack*"
          - "typescript"
        update-types:
          - "minor"
          - "patch"
      production-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "@types/*"
          - "eslint*"
          - "prettier*"
          - "jest*"
          - "webpack*"
          - "typescript"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore"
      include: "scope"
