/**
 * Golden-vector conformance ladder against the LOCMAF reference corpus
 * (Eyevinn/locmaf testdata/vectors, generated by the Go reference
 * implementation and pinned to the draft):
 *
 *   rung 1 — decode every wire object (objects/*.locmafobj) in group
 *            order without error;
 *   rung 2 — the decoded effective values equal effective/*.json;
 *   rung 3 — the canonical reconstruction is byte-identical to
 *            canonical/*.cmfc.
 *
 * The corpus is read from the sibling checkout of Eyevinn/locmaf in
 * the moq-workspace; when it is absent (e.g. standalone CI) the suite
 * skips itself.
 */
import { createHash } from "crypto";
import * as fs from "fs";
import * as path from "path";
import { fileURLToPath } from "url";

import { LocmafGroupState, decodeObject, parseInitContext } from "./decoder";
import { reconstructCanonical } from "./reconstruct";

const vectorsDir = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "../../../../locmaf/testdata/vectors",
);

interface EffectiveJson {
  rawBoxes?: { length: number; sha256: string };
  sampleCount?: number;
  bmdt?: number;
  sampleDescriptionIndex?: number;
  durations?: number[];
  sizes?: number[];
  flags?: number[];
  ctos?: number[];
  perSampleIVSize?: number;
  ivs?: string;
  hasSubsamples?: boolean;
  subsampleCounts?: number[];
  clearBytes?: number[];
  protectedBytes?: number[];
  genBoxes?: Array<{ name: string; payload: string }>;
  mdatLength?: number;
  mdatSha256?: string;
}

interface Manifest {
  name: string;
  locmafVersion: string;
  groups: number;
  objects: number;
  files: Record<string, string>;
}

function sha256Hex(bytes: Uint8Array): string {
  return createHash("sha256").update(bytes).digest("hex");
}

function hexToBytes(hex: string): Uint8Array {
  const out = new Uint8Array(hex.length / 2);
  for (let i = 0; i < out.length; i++) {
    out[i] = parseInt(hex.slice(2 * i, 2 * i + 2), 16);
  }
  return out;
}

const haveVectors = fs.existsSync(vectorsDir);
const describeVectors = haveVectors ? describe : describe.skip;
if (!haveVectors) {
  console.warn(`locmaf golden vectors not found at ${vectorsDir}; skipping`);
}

const caseNames = haveVectors
  ? fs
      .readdirSync(vectorsDir)
      .filter((n) => fs.existsSync(path.join(vectorsDir, n, "manifest.json")))
      .sort()
  : [];

describeVectors("locmaf v0.3 golden-vector conformance", () => {
  it("finds the corpus", () => {
    expect(caseNames.length).toBeGreaterThan(0);
  });

  for (const caseName of caseNames) {
    it(`case ${caseName}`, () => {
      const caseDir = path.join(vectorsDir, caseName);
      const manifest = JSON.parse(
        fs.readFileSync(path.join(caseDir, "manifest.json"), "utf8"),
      ) as Manifest;
      expect(manifest.locmafVersion).toBe("0.3");

      const ctx = parseInitContext(
        fs.readFileSync(path.join(caseDir, "init.mp4")),
      );

      const objectStems = Object.keys(manifest.files)
        .filter((f) => f.startsWith("objects/"))
        .map((f) => f.slice("objects/".length, -".locmafobj".length))
        .sort();
      expect(objectStems.length).toBe(manifest.objects);

      let currentGroup = "";
      let state = new LocmafGroupState();
      for (const stem of objectStems) {
        const group = stem.slice(0, stem.indexOf("_"));
        if (group !== currentGroup) {
          currentGroup = group;
          state = new LocmafGroupState();
        }

        const wire = fs.readFileSync(
          path.join(caseDir, "objects", `${stem}.locmafobj`),
        );
        const expectJson = JSON.parse(
          fs.readFileSync(
            path.join(caseDir, "effective", `${stem}.json`),
            "utf8",
          ),
        ) as EffectiveJson;
        const wantCanonical = new Uint8Array(
          fs.readFileSync(path.join(caseDir, "canonical", `${stem}.cmfc`)),
        );

        const result = decodeObject(new Uint8Array(wire), state, ctx);

        if (expectJson.rawBoxes !== undefined) {
          // A rawBoxes Object: verbatim bytes are their own canonical
          // form.
          expect(result.raw).toBeDefined();
          const raw = result.raw as Uint8Array;
          expect(raw.byteLength).toBe(expectJson.rawBoxes.length);
          expect(sha256Hex(raw)).toBe(expectJson.rawBoxes.sha256);
          expect(raw).toEqual(wantCanonical);
          continue;
        }

        expect(result.eff).toBeDefined();
        const eff = result.eff;
        if (eff === undefined) {
          throw new Error("unreachable");
        }

        // Rung 2: effective values.
        expect(eff.sampleCount).toBe(expectJson.sampleCount);
        expect(Number(eff.bmdt)).toBe(expectJson.bmdt);
        expect(eff.sampleDescriptionIndex).toBe(
          expectJson.sampleDescriptionIndex,
        );
        expect(eff.durations).toEqual(expectJson.durations);
        expect(eff.sizes).toEqual(expectJson.sizes);
        expect(eff.flags).toEqual(expectJson.flags);
        expect(eff.ctos).toEqual(expectJson.ctos);
        expect(eff.perSampleIVSize).toBe(expectJson.perSampleIVSize ?? 0);
        expect(sha256Hex(eff.ivs)).toBe(
          sha256Hex(hexToBytes(expectJson.ivs ?? "")),
        );
        expect(eff.hasSubsamples).toBe(expectJson.hasSubsamples ?? false);
        expect(eff.subsampleCounts).toEqual(expectJson.subsampleCounts ?? []);
        expect(eff.clearBytes).toEqual(expectJson.clearBytes ?? []);
        expect(eff.protectedBytes).toEqual(expectJson.protectedBytes ?? []);
        const wantGenBoxes = expectJson.genBoxes ?? [];
        expect(eff.genBoxes.length).toBe(wantGenBoxes.length);
        for (let i = 0; i < wantGenBoxes.length; i++) {
          expect(eff.genBoxes[i].name).toBe(wantGenBoxes[i].name);
          expect(eff.genBoxes[i].payload).toEqual(
            hexToBytes(wantGenBoxes[i].payload),
          );
        }
        expect(eff.mdatPayload.byteLength).toBe(expectJson.mdatLength);
        expect(sha256Hex(eff.mdatPayload)).toBe(expectJson.mdatSha256);

        // Rung 3: canonical bytes (mfhd sequence_number 0).
        const chunk = reconstructCanonical(ctx, eff, 0);
        expect(chunk).toEqual(wantCanonical);
      }
    });
  }
});
